apiVersion: v1
kind: Service
metadata:
  name: frontend-nodeport-svc
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
    - port: 8005              # порт сервиса внутри кластера
      targetPort: 8005         # порт контейнера
      nodePort: 31003         # внешний статический порт (30 000-32 767)
      protocol: TCP
