apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: pgvector
spec:
  serviceName: "pgvector"
  replicas: 1
  selector:
    matchLabels:
      app: pgvector
  template:
    metadata:
      labels:
        app: pgvector
    spec:
      containers:
      - name: postgres
        image: pgvector/pgvector:0.8.0-pg17
        imagePullPolicy: IfNotPresent
        ports:
        - name: postgresql
          containerPort: 5432
        env:
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: pgvector-secret
              key: POSTGRES_DB
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: pgvector-secret
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: pgvector-secret
              key: POSTGRES_PASSWORD
        volumeMounts:
        - name: data
          mountPath: /var/lib/postgresql/data
          subPath: data
        - name: initdb
          mountPath: /docker-entrypoint-initdb.d/01-create-extension.sql
          subPath: 01-create-extension.sql
      # ConfigMap с init‑SQL подключается как том
      volumes:
      - name: initdb
        configMap:
          name: pgvector-initdb
          defaultMode: 0755
      - name: data
        persistentVolumeClaim:
            claimName: pg-data-pvc
