
apiVersion: v1
kind: Service
metadata:
  name: pgvector
  labels:
    app: pgvector
spec:
  type: NodePort
  ports:
    - name: postgresql
      port: 5432
      targetPort: 5432
      nodePort: 31004
  selector:
    app: pgvector
