apiVersion: v1
kind: Service
metadata:
  name: backend-nodeport-svc        # поменяйте при необходимости
spec:
  type: NodePort
  selector:                    # ← вставьте свои метки
    app: backend
  ports:
    - port: 8000               # порт сервиса внутри кластера
      targetPort: 8000         # порт контейнера
      nodePort: 31002          # внешний статический порт (30 000-32 767)
      protocol: TCP
