apiVersion: v1
kind: Secret
metadata:
  name: pgvector-secret
type: Opaque
stringData:
  POSTGRES_DB: "postgres"
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "postgres"   # ← замените на свой пароль
