- name: Test Connection
  hosts: all
  become: true
  gather_facts: true

  pre_tasks:
  - name: update packages
    apt:
      update_cache: true
      cache_valid_time: 86400

  tasks:
  - name: Print some environment variables
    debug:
      msg: "TAG: {{lookup('ansible.builtin.env', 'APP_TAG_VERSION')}}"
