name: Code Clean-up
run-name:  Clean up push action at ${{ github.ref }}
on: [push]
jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v5
      - name: Setup libraries
        run: |
          cd frontend/
          uv sync
          uv pip install --editable .[dev]
      - name: Run Ruff linter
        run: |
          cd backend/
          uv run pre-commit run --all-files

  backend-tests:
    needs: [linting]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v5
      - name: Setup libraries
        run: |
          cd backend/
          uv sync
          uv pip install --editable '.[dev]'
      - name: Run Backend Tests
        run: |
          cd backend/
          uv run pytest --cov tests/ -v
